iptables -I INPUT -p tcp --dport 10000  -m state --state NEW -j ACCEPT
iptables -I INPUT -p tcp --dport 10001  -m state --state NEW -j ACCEPT
iptables -I INPUT -p tcp --dport 10002  -m state --state NEW -j ACCEPT
iptables -I INPUT -p tcp --dport 10003  -m state --state NEW -j ACCEPT
iptables -I INPUT -p tcp --dport 10004  -m state --state NEW -j ACCEPT
iptables -I INPUT -p tcp --dport 10005  -m state --state NEW -j ACCEPT
iptables -I INPUT -p tcp --dport 10006  -m state --state NEW -j ACCEPT
iptables -I INPUT -p tcp --dport 10007  -m state --state NEW -j ACCEPT
iptables -I INPUT -p tcp --dport 10008  -m state --state NEW -j ACCEPT
iptables -I INPUT -p tcp --dport 10009  -m state --state NEW -j ACCEPT
iptables -I INPUT -p tcp --dport 10010  -m state --state NEW -j ACCEPT
iptables -I INPUT -p tcp --dport 10011  -m state --state NEW -j ACCEPT
iptables -I INPUT -p tcp --dport 10012  -m state --state NEW -j ACCEPT
iptables -I INPUT -p tcp --dport 10013  -m state --state NEW -j ACCEPT
iptables -I INPUT -p tcp --dport 10014  -m state --state NEW -j ACCEPT
iptables -I INPUT -p tcp --dport 10015  -m state --state NEW -j ACCEPT
